server:
    port: 9000
    
jwt: 
    salt: asdf
    
spring:
    datasource:
        platform: mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/magichour?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: '@asd159450'
        
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/magichour?serverTimezone=UTC&characterEncoding=UTF-8
            username: root
            password: '@asd159450'
#    jpa:
#        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        open-in-view: false
#        show-sql: true
#        hibernate:
#            format_sql: true
#            ddl-auto: create
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
            descriptor:
                sql:
                    BasicBinder: TRACE
